import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../models/complaint_model.dart';
import '../services/firestore_service.dart';

final _firestoreServiceProvider = Provider<FirestoreService>((ref) {
  return FirestoreService();
});

final allComplaintsProvider = StreamProvider<List<ComplaintModel>>((ref) {
  final firestoreService = ref.watch(_firestoreServiceProvider);
  return firestoreService.streamAllComplaints();
});

final pendingComplaintsCountProvider = Provider<int>((ref) {
  final complaintsAsync = ref.watch(allComplaintsProvider);
  return complaintsAsync.when(
    data: (complaints) => complaints.where((c) => c.status == 'pending').length,
    loading: () => 0,
    error: (_, _) => 0,
  );
});

class ComplaintController {
  final FirestoreService _firestoreService = FirestoreService();

  Future<void> submitComplaint({
    required String userId,
    required String userName,
    required String userEmail,
    String? workerId,
    String? workerName,
    required String subject,
    required String message,
  }) async {
    final complaint = ComplaintModel(
      complaintId: '', // Generated by Firestore
      userId: userId,
      userName: userName,
      userEmail: userEmail,
      workerId: workerId,
      workerName: workerName,
      subject: subject,
      message: message,
      status: 'pending',
      createdAt: DateTime.now(),
    );

    await _firestoreService.createComplaint(complaint);
  }

  Future<void> resolveComplaint(String complaintId) async {
    await _firestoreService.updateComplaintStatus(complaintId, 'resolved');
  }
}
